### ISSUE TITLE
Query bus

### ISSUE THREAD

**Issue by gtoselli** [fizzbuds/ddd-toolkit#39]

**Comment by lucagiove** [comment]
We can quickly implement it like the command bus but I was thinking that there are less reason why this should be better than a direct method call. Probably just for inter bound context communication

**Comment by gtoselli** [comment]
I agree. Additionally using query bus instead of direct method call enable the "app" using the same structure. There are _cmd-handlers_ and _query-handlers_ folders.

Let's decide the interface. My proposal is
- `register` to add a query handler
- `run` or `execute` to run a query

@lucagiove, it's okay?
