### ISSUE TITLE
Simple transactional outbox

### ISSUE THREAD

**Issue by gtoselli** [fizzbuds/ddd-toolkit#4]

**Comment by lucagiove** [comment]
In case there are multiple repositories using the outbox pattern probably we should add a key to separate them otherwise it might use the wrong function.
Imagine
- Repo1 -> callback1 (not identified by the job payload)
- Repo2 -> callback2
The executeAllScheduledJobs on Repo1 can find scheduled jobs of Repo2 and execute callback1 on them instead of callback1

**Comment by gtoselli** [comment]
Now the scheduledBy field in outbox collection is the hostname.

We can concatenate hostname with something like _contextName_.

Maybe we can add a new field and use both scheduledBy and _contextName_

**Comment by lucagiove** [comment]
I would use a dedicated property in the document, that might be the name of the `aggregateName` that should be unique.
If we want to keep more generic for outbox `contextName` might work.
The issue with being too generic is that the aggregate method can't be `saveAndPublish`, but `saveAndRunJobs` that's not nice.
Maybe we can provide a dedicated interface of the outbox with names more for messaging that maps on a generic outbox, and same for repo might have different interfaces for different usages that maps to the same methods.

To discuss further the api interfaces of the lib here: #9

**Comment by gtoselli** [comment]
Today I wrote another Outbox class here on the issue branch. I introduced the _aggregateName_ to differentiate multiple instances on the same host.

For this milestone (0.1.0) to keep the outbox api closed to "messaging" concept. The outbox interface is

- scheduleEvent
- publishAllScheduledEvents
- publishAllEventsScheduledByMe
- startOutboxWatching

The OutboxEvent is

- eventPayload: any
- eventRoutingKey: string

Maybe in the future we will discuss a more generic interface.

**Comment by lucagiove** [comment]
I was thinking that probably os.hostname might be good for k8s but not in other environments where you might have multi processes on the same machine or in case physical hardware where hostname as not been customized.
What would be the drawback of using a uuid?

**Comment by gtoselli** [comment]
Yes I had thought of that.
_scheduledBy_ field should be the identifier of something go down or up in the same time (pod in k8s, process in local machine for example)

In case of two app that use ddd-toolkit lib on the same machine I think PID should be used.

In this implementation, the hostname is used as the default value of the _hostname_ argument of the Outbox class constructor.
We should find a better name!

If you use ddd-toolkit in the cloud, you will use the default value (os.hostame), but if you want you can pass something else (like process.pid). Will it be easy to explain this clearly in the documentation?

**Comment by lucagiove** [comment]
But if you go up and down pid changes. In k8s a restart probably the hostname is kept but at startup or shutdown all events are sent so it's not really useful having restoring a previous used value.

If we use a certainly unique value this mechanism can be transparent to the library user and it's a value under the library control.
What are the drawbacks?

**Comment by gtoselli** [comment]
So you would put in the _scheduledBy_ field a uuid generated for each instance of the outbox? Because then _aggregateName_ becomes useless.

Let's decide if it makes sense to combine the outbox instances in the same process (_host_ in the case of k8s)

**Comment by lucagiove** [comment]
_aggregateName_ meaning is mapping data with code callback, the uuid could be the same per node but yes if each instance is in charge than one random uuid would be useful for both aims

**Comment by gtoselli** [comment]
Is the uuid the same for every instance of the Outbox class in the same app?

In any case the aggregateName is needed for the data-behaviour mapping.
If however the uuid you want to make it global (for the whole app) it cannot be transparent and must be passed from the app to the library (and managed as a global provider in the nest DI)

**Comment by gtoselli** [comment]
I **might** have a good idea.
In order not to complicate our lives with the _leader_ instance and without having a _single point of failure_, a simple solution could be this

- each instance of the app has the cdc active
- when the change is received, each instance tries to update the document (simultaneously or almost simultaneously) by setting the status to processing.
- mongo guarantees that the `updateOne` is atomic and that only one of the competing operations can modify the document.
- the event publication is only taken by the instance that succeed (via modifiedCount) to update the status

What do you think @lucagiove?

```typescript
// cdc async iterator
for await (const change of this.activeChangeStream) {
	console.log('change!');
	await this.publishEvent((change as any).fullDocument);
}

private async publishEvent(outBoxModel: OutBoxModel) {
	const { modifiedCount } = await this.collection.updateOne(
		{ _id: outBoxModel._id },
		{ $set: { status: 'processing' } },
	);
	if (modifiedCount !== 1) {
		this.logger.log(`Already processing by another outbox`);
		return;
	}

	try {
		await this.publishEventFn(outBoxModel.event);
		await this.collection.updateOne(
			{ _id: outBoxModel._id },
			{
				$set: {
					status: 'published',
					publishedAt: new Date(),
				},
			},
		);
	} catch (e) {
		this.logger.warn(`Failed publishEventFn with ${JSON.stringify(outBoxModel.event)}`);
	}
}
```

**Comment by lucagiove** [comment]
I would remove this from the first beta and keep repo, event bus and command bus
