### ISSUE TITLE
Command sent without a registered command handler only log a warning

### ISSUE THREAD

**Issue by lucagiove** [fizzbuds/ddd-toolkit#69]
https://github.com/fizzbuds/ddd-toolkit/blob/07cf2361ec5e6f17cf83d29750e62085a72394d3/packages/ddd-toolkit/src/command-bus/local-command-bus.ts#L30

It happens often to forget to include the handled in module and command is not handled, why not throwing like in the sync method @gtoselli ?

**Comment by gtoselli** [comment]
The idea behind it was to simulate a distributed environment where you do not know if there is a handler for that command. I don't have a strong opinion on this, we can change it

**Comment by lucagiove** [comment]
Yes but since this is the implementation of a local version of a command bus it can help developer spot mistakes

**Comment by lucagiove** [comment]
https://github.com/fizzbuds/ddd-toolkit/commit/f34eaf63e6a538951cd21ff6f1ef733f3ce3ecb5
